-- Eventos personales (medico, clases, trabajo, etc.) fuera del concepto social de "plan".
-- Compatible con sincronizacion futura contra Google Calendar.

create table if not exists public.evento (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  estado text not null default 'ACTIVO' check (estado in ('ACTIVO', 'CANCELADO')),

  owner_user_id uuid not null references auth.users(id) on delete cascade,
  creado_por_user_id uuid not null references auth.users(id) on delete restrict,

  titulo text not null check (char_length(trim(titulo)) > 0 and char_length(titulo) <= 120),
  descripcion text null,
  categoria text not null default 'OTRO'
    check (categoria in ('TRABAJO', 'MEDICO', 'CLASE', 'PERSONAL', 'OTRO')),

  inicio_at timestamptz not null,
  fin_at timestamptz not null,
  all_day boolean not null default false,
  color text null,
  ubicacion_nombre text null,
  ubicacion_direccion text null,

  -- Soporte de sincronizacion externa.
  source text not null default 'LOCAL' check (source in ('LOCAL', 'GOOGLE')),
  google_calendar_id text null,
  google_event_id text null,
  sync_status text not null default 'SYNCED'
    check (sync_status in ('SYNCED', 'PENDING_CREATE', 'PENDING_UPDATE', 'PENDING_DELETE', 'ERROR')),
  last_synced_at timestamptz null,
  sync_error text null,

  constraint evento_date_range_chk check (fin_at >= inicio_at),
  constraint evento_google_unique unique (owner_user_id, google_calendar_id, google_event_id)
);

create index if not exists idx_evento_owner_inicio
  on public.evento (owner_user_id, inicio_at asc)
  where deleted_at is null and estado = 'ACTIVO';

create index if not exists idx_evento_owner_fin
  on public.evento (owner_user_id, fin_at asc)
  where deleted_at is null and estado = 'ACTIVO';

create index if not exists idx_evento_owner_source
  on public.evento (owner_user_id, source)
  where deleted_at is null;

create index if not exists idx_evento_google_ids
  on public.evento (owner_user_id, google_calendar_id, google_event_id)
  where source = 'GOOGLE' and deleted_at is null;

create or replace function public.fn_evento_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_evento_set_updated_at on public.evento;
create trigger trg_evento_set_updated_at
before update on public.evento
for each row
execute procedure public.fn_evento_set_updated_at();

alter table public.evento enable row level security;

drop policy if exists evento_select_own on public.evento;
create policy evento_select_own
on public.evento
for select
to authenticated
using (owner_user_id = auth.uid() and deleted_at is null);

drop policy if exists evento_insert_own on public.evento;
create policy evento_insert_own
on public.evento
for insert
to authenticated
with check (owner_user_id = auth.uid() and creado_por_user_id = auth.uid());

drop policy if exists evento_update_own on public.evento;
create policy evento_update_own
on public.evento
for update
to authenticated
using (owner_user_id = auth.uid() and deleted_at is null)
with check (owner_user_id = auth.uid());

drop policy if exists evento_delete_own on public.evento;
create policy evento_delete_own
on public.evento
for delete
to authenticated
using (owner_user_id = auth.uid() and deleted_at is null);
