create table if not exists public.route_cache (
  id bigint generated by default as identity primary key,
  origin_lat double precision not null,
  origin_lng double precision not null,
  dest_lat double precision not null,
  dest_lng double precision not null,
  polyline text not null,
  distance text null,
  duration text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists route_cache_origin_dest_key
  on public.route_cache (origin_lat, origin_lng, dest_lat, dest_lng);

create index if not exists route_cache_updated_at_idx
  on public.route_cache (updated_at desc);

create or replace function public.set_updated_at_route_cache()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists route_cache_set_updated_at on public.route_cache;
create trigger route_cache_set_updated_at
before update on public.route_cache
for each row
execute function public.set_updated_at_route_cache();

alter table public.route_cache enable row level security;

drop policy if exists route_cache_select_authenticated on public.route_cache;
create policy route_cache_select_authenticated
on public.route_cache
for select
to authenticated
using (true);

comment on table public.route_cache is
  'Cache de rutas entre coordenadas para reutilizar polyline, distancia y duracion sin volver a pedir Directions.';
